remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Mateus Vinicius Stoekly"
description: "Turning complex data into clear decisions. Explore my work in analytics, automation, and business intelligence."
show_downloads: true
google_analytics: G-VW92VCVEF7
