#logo: /assets/img/headshot_circle.png
#description: text below image
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Mateus Vinicius Stoekly]
description: [A short description of your site's purpose]
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
